[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xmtp-content-type-remote-attachment"
version = "0.0.0"
description = "XMTP remote attachment content type for Python."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
dependencies = [
  "xmtp-content-type-primitives",
  "xmtp-bindings",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"xmtp_content_type_remote_attachment" = ["py.typed"]
